# Environment Configuration
grid_size: 5          # Initial grid size
max_steps: 50         # Maximum steps per episode
dynamic_obstacles: 3  # Number of dynamic obstacles (added in later tasks)
goal_reward: 1.0      # Reward for reaching the goal
step_penalty: -0.1    # Penalty for each step
